version: "3.3"
services:

  ######################################################
  # SqlServer
  ######################################################
  sql:
    container_name: sql
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password@1234"
      ACCEPT_EULA: "Y"


  #######################################################
  #  Ecommerce
  #######################################################
  ecommerce:
    image: ecommerce
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: Dockerfile
    container_name: ecommerce
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_HTTP_PORT=5000





