name: CI

on:
  push:
    branches: [ "main" , "develop" ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main" , "develop" ]
    paths-ignore:
      - "README.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build ECommerce
        uses: ./.github/actions/build
        if: success()
        id: build-ecommerce-step
        with:
          project-path: 'src/ECommerce.Api'
          service-name: 'ECommerce'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test ECommerce
        uses: ./.github/actions/test
        if: success()
        id: test-ecommerce-step
        with:
          tests-path: 'tests/'
          reports-path: ${{ github.workspace }}/**/*.cobertura.xml
          reports-output-path: ${{ github.workspace }}/output/test-results
          service-name: 'ECommerce'
          token: ${{ secrets.GITHUB_TOKEN }}


