name: CI

on:
  push:
    branches: [ "main" , "develop" ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main" , "develop" ]
    paths-ignore:
      - "README.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

#      - name: Build and Test ECommerce
#        uses: ./.github/actions/build-test
#        if: success()
#        id: build-test-ecommerce-step
#        with:
#          project-path: 'src/ECommerce.Api'
#          tests-path: 'tests/'
#          # wildcard search for files with the ".cobertura.xml" extension in all subdirectories of the current directory
#          # https://www.jamescroft.co.uk/combining-multiple-code-coverage-results-in-azure-devops/
#          # https://stackoverflow.com/questions/53255065/dotnet-unit-test-with-coverlet-how-to-get-coverage-for-entire-solution-and-not
#          reports-path: ${{ github.workspace }}/**/*.cobertura.xml
#          reports-output-path: ${{ github.workspace }}/output/test-results
#          service-name: 'ECommerce'
#          token: ${{ secrets.GITHUB_TOKEN }}

#
#      - name: Update Release Drafter
#        if: ${{ github.ref == 'refs/heads/main' && success() }}
#        id: last_release
#        uses: release-drafter/release-drafter@v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Release Version Info
#        run:
#          echo "Release version is:" ${{ steps.last_release.outputs.tag_name }}

